### ISSUE TITLE
problem loading a new remote keys into the OCATS Rack

### ISSUE THREAD

**Issue by johndiaz2** [Comcast/cats#3] opened 2015-06-30 13:32 UTC
In the OCATS Rack.  We are trying to add a new remote control for a STB that is not Motorola or SA.
After recording the keys using the RedRat SignalDButil and following the instructions to load it in the OCATS, it did not work.  In the keymanager-service gui (web page), going to the Remotes tab and select Add, it gives the following error:

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: viewId:/listRemotes.jsf - View /listRemotes.jsf could not be restored.
                javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
                org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)

root cause

javax.faces.application.ViewExpiredException: viewId:/listRemotes.jsf - View /listRemotes.jsf could not be restored.
                com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205)
                com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
                com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
                com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
                javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
                org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)

note The full stack trace of the root cause is available in the JBoss Web/7.0.13.Final logs."

The suggested workaround to rename an existing remote with the newly loaded remote did not work either.

As of now there is no way to add a new remote to the CATS rack.

**Comment by sajayjk** [comment] 2015-06-30 13:59
Duplicate of issue #2

**Closed** 2015-06-30 17:47 UTC
Labels: duplicate
